### ISSUE TITLE
Game is not starting using /mg start

### ISSUE THREAD

**Issue by Goldenphelix** [AddstarMC/Minigames#215] opened 2019-04-28 08:20 UTC
* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When I run /mg start Snowfight nothing happens at all.
When I run it again, it says the game has already started, but I'm still in the
games waiting lobby.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**
Bug explained above and below.

* **What is the expected behavior?**
Minigames plugin should countdown for 30 seconds to allow people to join, teleport players to the game arena, sort them into Red, Blue, Yellow or Green team, countdown for 5 seconds and start the game.

* **What is the motivation / use case for changing the behavior?**
This issue appears to be the exact same thing as happening in issue #213 
Which continues to be unresolved.

* **Please tell us about your environment:**
- Spigot Version: Paper Spigot 1.13.2 
- Minigames version 1.13.1-SNAPSHOT-299

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Issue #213 
This is also my game config:
https://pastebin.com/eyi6JHwR

**Comment by Goldenphelix** [comment] 2019-04-28 09:18
Okay so I went on the AddStar server and saw it was using Minigames build #281 and so I downloaded that from https://jenkins.addstar.com.au/job/Minigames/281/ and now my game is working.
Strange!

**Comment by Narimm** [comment] 2019-04-28 11:16
Closed as duplicate of #213

**Closed by Narimm** 2019-04-28 11:16 UTC
