### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by michaeldriskell** [AddstarMC/Minigames#123] opened 2017-07-19 16:11 UTC
I love this plugin. Some things I would like to say:

Minigames Regions have a holographic sign that every player can see and its ugly. I haven't been able to find a way to disable it.

I don't think there is a leaderboard option. It would be nice to have the option to see the best scores of the week or all time. With placeholder support so it could be used in holographic or wooden signs.

There should be a way to add '1' to the players score every second, so their final score is their time it took to complete the course. I tried setting up a redstone 1 sec repeating loop that ran a command every second but it was really complicated and ultimately wouldn't work.

Lastly, I wish there was a way to edit the sign layout. Each sign doesn't need to say [Minigame].. just Join or Spectate. I looked through the configs and wiki and didnt see any way to edit it.

I would pay for all of these options. Maybe Minigames could have a premium version in the future with more features?

**Comment by jupiter1390** [comment] 2017-07-27 03:11
You can make leaderboard by minigame plugin's option called scoreboard, based on mySQL database, showing top scores(or top death or something, can be configurable) on updated wooden signs

For adding 1 secs to players, use region&node configuration and add event tick(it activates every 1 sec) to give everyone 1 score

For sign layout, why don't you use custom join signs with VariableTriggers or something? I am using Deluxemenu for minigame joining, giving appropriate icons and names for each minigames

**Comment by Narimm** [comment] 2017-09-04 03:15
Closed as not a bug

**Closed by Narimm** 2017-09-04 03:15 UTC
Labels: Configuration, invalid
