### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by Noket** [AddstarMC/Minigames#23] opened 2014-08-07 02:28 UTC
- Autobalance feature is not configurable, and can interfere heavily in team gametypes. Often times, players switch teams 3 to 4 times throughout a game.

- There is no option or ability to toggle fly while in a minigame.

- Loadouts cannot be assigned to teams.

- Minigames breaks when a server restarts while there is a minigame running. The players (upon restart) are no long in the minigame, are not restricted from griefing .. and do not have the option of warping to the lobby location or a non-griefable area.

- Individual team lives are not configurable.

- A minigame where "Creative Mode" is Enabled does not work. Players receive "You cannot fly during a minigame" error message

**Comment by orkun1675** [comment] 2015-02-12 23:08
+1

**Comment by Noket** [comment] 2015-02-13 04:15
sadly, I think he's abandoned the project

**Comment by orkun1675** [comment] 2015-02-13 10:22
Could someone take over?

**Comment by elliot-labs** [comment] 2015-02-13 16:02
What language is it written in?

On Fri, Feb 13, 2015 at 5:22 AM, orkun1675 <notifications@github.com> wrote:

> Could someone take over?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Razz0991/Minigames/issues/23#issuecomment-74233002>.
>



-- 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by orkun1675** [comment] 2015-02-13 17:30
Java using the bukkit api of course.

**Comment by elliot-labs** [comment] 2015-02-13 17:32
I guess that I could try to take it over, I don't know java but this would be a good starting place. I have been meaning to learn a language besides Windows/Unix Shell...

**Comment by elliot-labs** [comment] 2015-02-13 17:33
It will most likely take a while to learn how to code so don't expect anything soon. I guess that I could try compiling it for 1.8 first... That should not be hard...

**Comment by elliot-labs** [comment] 2015-02-13 17:34
Wait, the author was active 8 days ago... I don't think this has been abandoned...

**Comment by Noket** [comment] 2015-02-14 00:49
Elliot, would you like to work together on it? I can teach you some of the
Java basics and how to use more modern java tools such as collections.

He was active on another project, but I haven't seen him touch minigames in
months.

**Comment by Schmoller** [comment] 2015-02-14 08:34
I just want to let you know that Minigames is not abandoned and continues to get updates. There hasnt been an update on bukkit for a while but there have been plenty of dev builds. We hope to push a new version to bukkit soon.

As for the original purpose of this, some of these requests are currently available in the dev builds at http://jenkins.addstar.com.au/job/Minigames/

**Comment by elliot-labs** [comment] 2015-02-14 16:38
@Schmoller 
What about spigot? are you going to recompile for spigot?

**Comment by elliot-labs** [comment] 2015-02-14 16:40
@Noket I would love to learn Java, and have been meaning to get into more advanced programming some time or later (I know a small amount of ms VB...)

**Comment by Schmoller** [comment] 2015-02-15 02:09
@elliot-labs We have decided to push more towards spigot as it provides some great features bukkit should have, but we will not require people to have spigot. So basically you will get extra content if you are on spigot

**Comment by elliot-labs** [comment] 2015-02-15 03:30
@Schmoller Awesome, a good move (Until the lawyers get them for the bukkit code they are hosting...)

**Comment by Noket** [comment] 2015-02-15 04:00
Well, to my understanding .. Spigot doesn't actually use Bukkit code. It
just wraps it .. which implies that the PO'd bukkit developer might not be
able to take down spigot. Then again, abstraction is a strange mysterious
creature to me. So, somebody else could probably explain it better.

**Comment by addstar** [comment] 2016-03-08 10:12
Closing old unhandled issues, re-open if you still have an issue.

**Closed by addstar** 2016-03-08 10:12 UTC
