### ISSUE TITLE
Some region&node error

### ISSUE THREAD

**Issue by jupiter1390** [AddstarMC/Minigames#95] opened 2017-04-22 09:49 UTC
1. message will always be announced twice to user, even though it is triggered once
2. 'set score' node will be reset to value 0 on sercer restart

**Comment by jupiter1390** [comment] 2017-04-27 06:33
+When selecting region with minigame tool, fire particles which show the box would fly away, it didn't fly away before

**Comment by Narimm** [comment] 2017-04-27 11:40
Unless you can provide the specific times messages are doubled and we cant reproduce the node score reset either.
I will look into the particles

**Comment by jupiter1390** [comment] 2017-04-27 12:37
@Narimm
every message will be anounced twice, even trigger number is set to 1

**Comment by Narimm** [comment] 2017-05-10 02:24
So again can you please post a server log of the occurance and the config that generates it

**Comment by jupiter1390** [comment] 2017-05-12 07:53
@Narimm
Will upload later

**Comment by jupiter1390** [comment] 2017-07-27 03:31
@Narimm
It doesn't have any server error logs, no minigame error logs detected. I think it is not a serious error but just a bug

**Comment by Narimm** [comment] 2017-10-19 11:48
This is being corrected in a new feature closing for now

**Closed by Narimm** 2017-10-19 11:48 UTC
Labels: More Information Needed
