### ISSUE TITLE
/minigame set <Minigame> start [player number] , same start position bug

### ISSUE THREAD

**Issue by DragonbornCommunity** [AddstarMC/Minigames#178] opened 2018-03-17 03:03 UTC
**Note: for support questions, please use SpigotMC.org**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x ] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem, screenshots ok**

I set more start position for players in a multiplayer type minigame , but on the join of the players in the minigame they start from the same position, I tried with the command /minigame set <Minigame> start [player number] and also with the tool , with the tool I can see the skeleton head for the start position,I tried everything .

* **What is the expected behavior?**
more start position

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
- Spigot Version:  1.12.2
- Minigames version: 1.12.1-  and 1.12

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Narimm** [comment] 2018-03-17 09:22
Closed as a Duplicate of #169

**Closed by Narimm** 2018-03-17 09:22 UTC
Labels: duplicate
